// src/components/form/SignInForm/index.tsx
'use client'

import Router from "next/router"
import { useSignInForm } from '@/hooks/useForm'
// import { SignInFieldsForm } from '@/types/form/signIn'
import { AppButton, AppColumn, AppColumns, AppDivisor, AppForm, AppInput } from '@/components/base'
import { AppText } from '@/components/base/text/AppText'
import { api } from '@/services/api'
import { useStoreAuth } from '@/hooks/useStoreAuth'
import { useStoreSystem } from '@/hooks/useStoreSystem'
import { useStoreFinance } from '@/hooks/useStoreFinance'
import { $ } from "@/utils"

export const SignInForm = () => {
  const { dispatchSetUser } = useStoreAuth()
  const { dispatchSetPeriod, dispatchSetWalletPanelId } = useStoreSystem()
  const { dispatchSetFinanceWallet, dispatchSetFinanceOrigin, dispatchSetFinanceTag, dispatchSetFinanceList } = useStoreFinance()
  const { fields, onChangeField } = useSignInForm()


  const getToken = async () => {
    try {
      const { data: { token } } = await api.auth.signIn({
        form: {
          email: fields.email,
          password: fields.password
        }
      })

      const key = process.env.NEXT_PUBLIC_KEY_TOKEN || ''

      $.setToken(token)

    } catch (error) {
      console.log('getToken - error', error)
    }
  }

  const getUserData = async () => {
    try {
      const { data: { period, user } } = await api.user.data()

      dispatchSetUser(user)
      dispatchSetPeriod(period)
    } catch (error) {
      console.log('getUserData - error', error)
    }
  }

  const getFinanceData = async () => {
    try {
      const financeResult = await api.finance.data()

      dispatchSetWalletPanelId(financeResult.data.wallet_panel.id)
      dispatchSetFinanceWallet(financeResult.data.wallet)
      dispatchSetFinanceOrigin(financeResult.data.origin)
      dispatchSetFinanceTag(financeResult.data.tag)
      dispatchSetFinanceList({
        originType: financeResult.data.originType,
        status: financeResult.data.status,
        type: financeResult.data.type,
      })
    } catch (error) {
      console.log('getFinanceData - error', error)
    }
  }

  const onSubmit = async () => {
    try {
      await getToken()
      await getUserData()
      await getFinanceData()
    } catch (error) {
      console.log('onSubmit - error', error)
    }

    Router.push('/panel/finance')
    // signIn({
    //   id: 1,
    //   name: 'nino',
    //   email: 'email.com'
    // })
  }

  return (
    <AppForm
      onSubmit={onSubmit}
      containersx={{ p: 3, maxWidth: 325 }}
    >
      <AppText variant='h3'>
        Bem Vindo
      </AppText>

      <AppDivisor />

      <AppColumns>
        <AppColumn xs={12} >
          <AppInput
            autoComplete='off'
            label="Email"
            type="text"
            value={fields.email}
            onChange={({ target }) => {
              onChangeField({
                email: target.value,
              })
            }}
          />
        </AppColumn>
        <AppColumn xs={12}>
          <AppInput
            label="Senha"
            type="password"
            value={fields.password}
            onChange={({ target }) => {
              onChangeField({
                password: target.value,
              })
            }}
          />
        </AppColumn>
        <AppColumn xs={12}>
          <AppButton type="submit">Entrar</AppButton>
        </AppColumn>
      </AppColumns>
    </AppForm>
  )
}

// src/components/views/SignInForm.vue
<script setup lang="ts">
import { reactive } from "vue";
import { useRouter } from "vue-router";
import api from "@/services/api";
import { SignInForm } from "@/types";
import useStoreSystem from "@/hooks/useStoreSystem";

const storeSystem = useStoreSystem();
const router = useRouter();

const form = reactive<SignInForm>({
  email: "test1@email.com",
  password: "1234",
  // email: "",
  // password: "",
});

const signIn = async (): Promise<void> => {
  const resultSignIn = await api.auth.signIn({
    email: form.email,
    password: form.password,
  });

  if (!resultSignIn.status) {
    console.log("fazer oo alerta");
    return;
  }

  await storeSystem.setToken(resultSignIn.data.token);

  const resultDataUser = await api.user.data();

  if (!resultDataUser.status) {
    console.log("fazer oo alerta");
    return;
  }

  await storeSystem.signIn({
    user: resultDataUser.data.user,
    period: resultDataUser.data.period,
  });

  router.push({ name: "dashboard" });
};

// const teste = async () => {
//   const result = await api.user.data();

//   console.log("result", result);
// };
</script>

<template>
  <!-- <AppButton content="Entrar" class="w-full" @click="teste" /> -->

  <AppForm @onSubmit="signIn" class="signIn__form">
    <AppText content="Bem vindo" size="display" />

    <AppDivisor />

    <AppInput label="Email" v-model="form.email" />
    <AppInput
      label="Senha"
      type="password"
      class="mb-4"
      v-model="form.password"
    />

    <AppButton content="Entrar" class="w-full" type="submit" />

    <AppDivisor />

    <AppTextLink
      class="w-full"
      content="Esqueci minha senha!"
      @click="() => router.push({ name: 'forgot-password' })"
    />
    <AppTextLink
      class="w-full"
      content="Quero me registar!"
      @click="() => router.push({ name: 'sign-up' })"
    />
  </AppForm>
</template>

<style lang="scss" scoped>
.signIn__form {
  @apply w-72 p-3 border border-gray-200 rounded shadow;
}
</style>
